name = "kt-port"
product-name = "kt-port"
version = "0.1.0"
identifier = "io.github.kazma233.kt-port"
publisher = "kazma233"
description = "A desktop port viewer and process killer"
homepage = "https://github.com/kazma233/play-projects/kt-port"
copyright = "Copyright (c) 2026 kazma233"
out-dir = "dist"
binaries-dir = "target/release"
binaries = [
  { path = "kt-port", main = true }
]
icons = ["assets/icon.*"]
before-packaging-command = "cargo build --release --locked"
